{% set build = 2 %}
{% set version = '2.4.9b' %}
{% set mpi = environ.get('MPI') or 'mpich' %}
{% set mpi_version = {'mpich':'>=3.2', 'openmpi':'>=2.0'}.get(mpi,'') %}

package:
  name: mpe
  version: {{version}}

source:
  git_url: https://github.com/pmodels/mpe
  git_rev: master

requirements:
  build:
    - autoconf
    - libtool
    - openjdk
    - {{mpi}} {{mpi_version}}
  run:
    - openjdk
    - {{mpi}} {{mpi_version}}

build:
  number: {{build}}
  string: {{mpi}}_{{build}}
  skip: true # [win]

test:
  files:
    - test/helloworld.c
  commands:
    - command -v mpecc
    - mpecc -mpilog -show
    - mpecc -mpilog test/helloworld.c -o helloworld
    - mpiexec -n 5 ./helloworld
    - clog2TOslog2 helloworld.clog2
    - slog2print -c helloworld.slog2

about:
  home: http://www.mcs.anl.gov/research/projects/perfvis/software/MPE/
  summary: 'MPE: MPI Parallel Environment'
  license: MIT
  license_file: COPYRIGHT
